[package]
name = "sn0int"
version = "0.19.1"
description = "Semi-automatic OSINT framework and package manager"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/sn0int"
categories = ["command-line-utilities"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "kpcyrd/sn0int" }

[workspace]
members = ["sn0int-common",
           "sn0int-registry",
           "sn0int-std"]

[package.metadata.deb]
extended-description = """\
sn0int (pronounced /snoÉªnt/) is a semi-automatic OSINT framework and package
manager. It was built for IT security professionals and bug hunters to gather
intelligence about a given target or about yourself. sn0int is enumerating
attack surface by semi-automatically processing public information and mapping
the results in a unified format for followup investigations."""
section = "utils"
priority = "optional"
depends = "$auto, publicsuffix"
build-depends = "pkg-config, libsqlite3-dev, libseccomp-dev, libsodium-dev, publicsuffix"
assets = [
    ["target/release/sn0int", "usr/bin/", "755"],
]

[features]
sqlite-bundled = ["libsqlite3-sys/bundled"]

[dependencies]
sn0int-common = { version="0.11.0", path="sn0int-common" }
sn0int-std = { version="=0.19.0", path="sn0int-std" }
rustyline = "6.0"
log = "0.4"
env_logger = "0.7"
hlua-badtouch = "0.4"
structopt = "0.3"
failure = "0.1"
rand = "0.7"
colored = "2"
lazy_static = "1.0"
shellwords = "1.0"
diesel = { version = "1.0.0", features = ["sqlite", "chrono"] }
diesel_migrations = { version = "1.3.0", features = ["sqlite"] }
libsqlite3-sys = { version = "0.18.0", features = ["bundled-windows"] }
chrono = { version = "0.4", features = ["serde"] }
dirs = "3.0"
url = "2.0"
percent-encoding = "2.1"
#chrootable-https = { path = "../chrootable-https" }
chrootable-https = "0.15.2"
base64 = "0.12"
data-encoding = "2.1.2"
serde_urlencoded = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
crossbeam-channel = "0.4"
ctrlc = "3.1"
opener = "0.4"
separator = "0.4"
maplit = "1.0.1"
sloppy-rfc4880 = "0.1.5"
regex = "1.0"
toml = "0.5"
threadpool = "1.7"
atty = "0.2"
semver = "0.10"
bytes = "0.4"
bytesize = "1.0"
ipnetwork = "0.17"
strum = "0.19"
strum_macros = "0.19"
embedded-triple = "0.1.0"

digest = "0.9"
md-5 = "0.9"
sha-1 = "0.9"
sha2 = "0.9"
sha3 = "0.9"
hmac = "0.9"

walkdir = "2.2"
nude = "0.3"
glob = "0.3.0"
os-version = "0.1.1"

[target.'cfg(target_os="linux")'.dependencies]
caps = "0.4"
#syscallz = { path="../syscallz-rs" }
syscallz = "0.14.0"
nix = "0.18"

[target.'cfg(target_os="openbsd")'.dependencies]
pledge = "0.4"
unveil = "0.2.0"

[dev-dependencies]
#boxxy = { path = "../boxxy-rs" }
boxxy = "0.11"
tempfile = "3.0"
